### ISSUE TITLE
About the versions of Pytorch & torchvision

### ISSUE THREAD

**Issue by gordonguo98** [YuvalNirkin/hyperseg#1]
Hi, which versions of Pytorch & torchvision does this repo support? When I use Pytorch 1.8.0 and torchvision 0.9.0 there are some import errors.

**Comment by YuvalNirkin** [comment]
I did test the repository with those versions, it should be working.
Can you provide the errors please?

**Comment by gordonguo98** [comment]
> I did test the repository with those versions, it should be working.
> Can you provide the errors please?

Hi, thanks for your reply, here's what I did and the screen output:
(pytorch-env) hm@hm-System:~/hyperseg$ python configs/train/cityscapes_efficientnet_b1_hyperseg-s.py
Traceback (most recent call last):
  File "configs/train/cityscapes_efficientnet_b1_hyperseg-s.py", line 7, in <module>
    from hyperseg.datasets.seg_transforms import RandomHorizontalFlip, RandomResize, RandomCrop, ToTensor, Normalize
  File "/home/hm/hyperseg/datasets/seg_transforms.py", line 12, in <module>
    from torchvision.transforms.transforms import _pil_interpolation_to_str
ImportError: cannot import name '_pil_interpolation_to_str'

I have Pytorch 1.8.1(py3.6_cuda10.2_cudnn7.6.5_0) & torchvison 0.9.1(py36_cu102) installed in my conda environment. Looking forward to your reply.

**Comment by YuvalNirkin** [comment]
Thank you for the feedback!
There was an issue with torchvision v0.9.1 and it is now fixed.
Please pull the update and try again.

**Comment by gordonguo98** [comment]
> Thank you for the feedback!
> There was an issue with torchvision v0.9.1 and it is now fixed.
> Please pull the update and try again.

Many thanks!
