### ISSUE TITLE
What is the difference among models/hyperseg_v0_1.py, models/hyperseg_v0_2.py, models/hyperseg_v1_0.py,  models/hyperseg_v1_0_unify.py, 

### ISSUE THREAD

**Issue by tricoffee** [YuvalNirkin/hyperseg#10]
What is the difference among models/hyperseg_v0_1.py, models/hyperseg_v0_2.py, models/hyperseg_v1_0.py,  models/hyperseg_v1_0_unify.py

**Comment by YuvalNirkin** [comment]
Legacy models for getting the paper results.
**hyperseg_v1_0_unify.py** is the latest and most efficient model.
