### ISSUE TITLE
Dataset not found or incomplete.

### ISSUE THREAD

**Issue by leo-hao** [YuvalNirkin/hyperseg#11]
```
(liuhaomag) cv428@428:~/data/LH/hyperseg$ python configs/train/cityscapes_efficientnet_b1_hyperseg-m.py
Traceback (most recent call last):
  File "configs/train/cityscapes_efficientnet_b1_hyperseg-m.py", line 46, in <module>
    scheduler=scheduler, pretrained=pretrained, model=model, criterion=criterion, batch_scheduler=batch_scheduler)
  File "/home/cv428/data/LH/hyperseg/train.py", line 187, in main
    train_dataset = obj_factory(train_dataset, transforms=train_transforms)
  File "/home/cv428/data/LH/hyperseg/utils/obj_factory.py", line 57, in obj_factory
    return obj_exp(*args, **kwargs)
  File "/home/cv428/data/LH/hyperseg/datasets/cityscapes.py", line 156, in __init__
    raise RuntimeError('Dataset not found or incomplete. Please make sure all required folders for the'
RuntimeError: Dataset not found or incomplete. Please make sure all required folders for the specified "split" and "mode" are inside the "root" directory
 
```

**Comment by leo-hao** [comment]
i have no idea about the folders for the specified "split" and "mode" are inside the "root" directory

**Comment by YuvalNirkin** [comment]
You must download the [CityScapes](https://www.cityscapes-dataset.com/) dataset to the directory specified in the config file first.

**Comment by leo-hao** [comment]
Hi! Thanks for your reply. I have put data/cityscapes under the hyperseg. And i set the the data_dir='/home/data/userleo/Documents/code/hyperseg/data/cityscapes'
 in config/train/cityscapes_efficientnet_b1_hyperseg-m.py, occurs the same issue where data_dir='/data/cityscapes'. I wonder know where the config should i modify . 
Looking forward to your reply~
![image](https://user-images.githubusercontent.com/20486586/134756563-c69982da-4623-4b3c-b9bf-0a4c13918f55.png)

**Comment by YuvalNirkin** [comment]
Make sure the cityscapes root directory contains the following directories:
leftImg8bit
----train
----val
----test
gtFine
----train
----val
----test

Additionally make sure that *data_dir* variable does actually point to the cityscapes root directory.

**Comment by leo-hao** [comment]
Thank you for your help. This is the second time I ran a code experiment. I downloaded the cityscapes dataset last time. I forgot that gtFine is also part of it. This stupid question has bothered me for a long time. Thank you again for your reply, I wish you success in your work and create greater glories.
