### ISSUE TITLE
No module named 'hyper_seg'

### ISSUE THREAD

**Issue by leo-hao** [YuvalNirkin/hyperseg#12]
Because the training failed, I tried to download cityscapes_efficientnet_b1_hyperseg-m.pth to hyperseg/weights, and renamed it to model_best.pth,
I try
python test.py 'weights'  \
-td "hyper_seg.datasets.cityscapes.CityscapesDataset('data/cityscapes',split='val',mode='fine')"\ -it "seg_transforms.LargerEdgeResize([512,1024])" \
--gpus 0
![image](https://user-images.githubusercontent.com/20486586/134766931-0433874d-e7aa-44c0-919c-b39a7e848387.png)
Looking forward to your reply！

**Comment by YuvalNirkin** [comment]
You need to add the parent directory of the repository to PYTHONPATH.
That will be **~/Documents/code** in your case.

**Comment by leo-hao** [comment]
Dear doctor Nirkin, thank you for your reply on this question. 
In fact, I added the following sentence into the environment variable before training
export PYTHONPATH=$PYTHONPATH:/home/data/userleo/Documents/code

And  I just tried to add
export PYTHONPATH=$PYTHONPATH:~/Documents/code
export PYTHONPATH=$PYTHONPATH:/Documents/code
Then, I source ~/.bashrc

run the test order
But still the same error.

Looking forward to your reply!

**Comment by leo-hao** [comment]
Dear doctor Nirkin, I found the error after reading the code. The test command you gave in the README.md file does not require an underscore.

**Comment by Jun-jieChen** [comment]
@leo-hao  I meet the same problem, how do you deal with it?

**Comment by YuvalNirkin** [comment]
I fixed the README, thanks!

**Comment by shengxing-phd** [comment]
Hi, I have the same problem, how did you add the directory to the PythonPath, please?
