### ISSUE TITLE
The difference between the Resize(512, 1024) and LargerEdgeResize(512, 1024)

### ISSUE THREAD

**Issue by J-JunChen** [YuvalNirkin/hyperseg#14]
Hello! @YuvalNirkin,

I would like to know what is the difference between the `torchvision.transforms.Resize` function and your designed `hyperseg.datasets.seg_transforms.LargerEdgeResize` function?

The results of global accuray and mIoU are slightly difference when I use these two transfromation separably in test phrase.

Wish your reply.

**Comment by YuvalNirkin** [comment]
They only differ when `size` is a single number. In Resize the smaller edge will be matched to `size` while in LargerEdgeResize, the larger edge will be matched to `size`.
