### ISSUE TITLE
ModuleNotFoundError:No module named ‘hyperseg’

### ISSUE THREAD

**Issue by Rebufleming** [YuvalNirkin/hyperseg#22]
I encountered this error when I was training the model, and when I deleted all the "hyperseg" in the code, this error was not reported. Is this the right thing to do?

**Comment by YuvalNirkin** [comment]
It's best to add the parent directory of the repository to PYTHONPATH.

**Comment by Rebufleming** [comment]
> 

Thank you! It works

**Comment by shengxing-phd** [comment]
Hi, I have the same problem, how did you add the directory to the PythonPath, please?

**Comment by Rebufleming** [comment]
> 

我的方法还是把那些”hyperseg“都删了，因为每次都添加到python path很麻烦，那个好像是一次性的。你可以在网上搜一下怎么加入python path，这个是我之前做的，我现在忘了。

**Comment by shengxing-phd** [comment]
> > 
> 
> 我的方法还是把那些”hyperseg“都删了，因为每次都添加到python path很麻烦，那个好像是一次性的。你可以在网上搜一下怎么加入python path，这个是我之前做的，我现在忘了。

非常感谢！！
