### ISSUE TITLE
About Test bug

### ISSUE THREAD

**Issue by Haodong-Lei-Ray** [YuvalNirkin/hyperseg#27]
While I use the test script of vocdataset, it will occur a bug----[Errno 2] No such file or directory: 'data/vocsbd/Vocdevkit/V0C2012/3PEGImages/2007_000033.jp9. How to deal with it?

**Comment by Haodong-Lei-Ray** [comment]
I find what‘s happen. While I delete old documents about that path. The problem is dealt with. So just redownload.

**Comment by YuvalNirkin** [comment]
Great.
