### ISSUE TITLE
MIoU on Pascal VOC is about 0.7 with 50 epoches

### ISSUE THREAD

**Issue by dansonc** [YuvalNirkin/hyperseg#3]
Thank you for your sharing.
I have tried to retrain the model on Pascal VOC dataset, but the miou is only about 0.7 after 50 epoches and it hardly increased, may I know is it correct? or should I continue the training for 160 epoches?

**Comment by YuvalNirkin** [comment]
Our model converged by epoch 64.
Either let it run a little bit more or try again.

**Comment by dansonc** [comment]
Thank you for your reply and help, I rerun it again and the results seems better. I don't understand the printed logger information on the "bench", e.g., ... bench: [iou: 0.8000 (0.7500); ] ..., so, which value is the MIoU?

**Comment by YuvalNirkin** [comment]
The first value is the mIoU. The second value is the average over the entire epoch (if the first value is higher than the second value it means the model is improving).
