### ISSUE TITLE
Have you tried your new method on face segmentation?

### ISSUE THREAD

**Issue by lastapple** [YuvalNirkin/hyperseg#9]
Have you compared your new method with your old one "Deep face segmentation in extremely hard conditions"? I'm looking for the latest open source method for face segmentation which can handle occlusions like hands.

**Comment by YuvalNirkin** [comment]
We haven't compared to our previous segmentation model.
We have a newer face segmentation model here: [https://github.com/YuvalNirkin/fsgan](https://github.com/YuvalNirkin/fsgan).
